### ISSUE TITLE
'bias_initializer' problem

### ISSUE THREAD

**Issue by Pongsasit** [manicman1999/Matchue-StyleGAN#1]
Thank you for your video. I found you on youtube and try to do this amazing GAN along with you, But I got this problem.
- call() got an unexpected keyword argument 'bias_initializer'

def g_block(input_tensor, latent_vector, filters):
    gamma = Dense(filters)(latent_vector, bias_initializer = 'ones')
    beta = Dense(filters)(latent_vector)
    
    out = UpSampling2D()(input_tensor)
    out = Conv2D(filters, 3, padding = 'same')(out)
    out = Lambda(AdaIN)([out, gamma, beta])
    out = Activation('relu')(out)
    
    return out

#Latent input
latent_input = Input([64])

#Map latent input
latent = Dense(64, activation = 'relu')(latent_input)
latent = Dense(64, activation = 'relu')(latent)
latent = Dense(64, activation = 'relu')(latent)

#Reshape to 4x4x64
x = Dense(4*4*64, activation = 'relu')(latent_input)
x = Reshape([4, 4, 64])(x)

#Size: 4x4x64
x = g_block(x, latent, 64)

#Size: 8x8x64
x = g_block(x, latent, 32)

#Size: 16x16x32
x = g_block(x, latent, 16)

#Size: 32x32x16
x = g_block(x, latent, 8)

#Size: 64x64x8, make RGB with values between 0 and 1
image_output = Conv2D(3, 1, padding = 'same', activation = 'sigmoid')(x)

#Make Model
generator = Model(inputs = latent_input, outputs = image_output)

#Model Summary
generator.summary()

call() got an unexpected keyword argument 'bias_initializer'

Could you tell me, What if bias_initializer didn't set. Thank you.

**Comment by manicman1999** [comment]
Thank you for spotting the issue. I changed the bias_initializer parameter to be in the wrong brackets when updating the code without testing. It is fixed now.
